"""add symbol column to stock_daily table

Revision ID: 20260221_2300
Revises: 20260221_0018
Create Date: 2026-02-21 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260221_2300'
down_revision = '20260221_0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add symbol column after third_code column
    op.add_column('stock_daily', sa.Column('symbol', sa.String(length=32), nullable=True))
    
    # Fill symbol column from stock_basic table
    op.execute("""
        UPDATE stock_daily 
        SET symbol = (
            SELECT sb.symbol 
            FROM stock_basic sb 
            WHERE sb.source = stock_daily.source 
            AND sb.third_code = stock_daily.third_code
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_daily', 'symbol')
    # ### end Alembic commands ###
