"""remove foreign key constraints from concept tables

Revision ID: 20260221_0022
Revises: 20260221_0018
Create Date: 2026-02-21 00:22:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260221_0022'
down_revision = '20260221_0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除concept_stock表的外键约束
    op.drop_constraint('concept_stock_concept_id_fkey', 'concept_stock', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 重新添加外键约束（如果需要回滚）
    op.create_foreign_key('concept_stock_concept_id_fkey', 'concept_stock', 'concept', ['concept_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
