"""add index on stock_daily.third_code

Revision ID: 20260221_0018
Revises: 457ca5f5dfdb
Create Date: 2026-02-21 00:18:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260221_0018'
down_revision = '457ca5f5dfdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stock_daily_third_code', 'stock_daily', ['third_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_daily_third_code', table_name='stock_daily')
    # ### end Alembic commands ###
