"""add stock daily tables

Revision ID: 5f4c9e8a6bf5
Revises: c1add_stock_basic
Create Date: 2026-02-20 08:20:09.709501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4c9e8a6bf5'
down_revision = 'c1add_stock_basic'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('third_code', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('pre_close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('change', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('pct_chg', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('vol', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('adj_factor', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('turnover_rate', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('turnover_rate_f', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pe_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ps_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dv_ratio', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dv_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('total_share', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('float_share', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('free_share', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_mv', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('circ_mv', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'third_code', 'trade_date', name='uq_stock_daily_key')
    )
    op.create_index(op.f('ix_stock_daily_trade_date'), 'stock_daily', ['trade_date'], unique=False)
    op.create_table('stock_daily_sync_failure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('third_code', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_daily_sync_failure')
    op.drop_index(op.f('ix_stock_daily_trade_date'), table_name='stock_daily')
    op.drop_table('stock_daily')
    # ### end Alembic commands ###
