"""rename financial_indicator to stock_financial and add symbol column

Revision ID: 20260221_2310
Revises: 20260221_2300
Create Date: 2026-02-21 23:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260221_2310'
down_revision = '20260221_2300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add symbol column after third_code column
    op.add_column('financial_indicator', sa.Column('symbol', sa.String(length=32), nullable=True))
    
    # Rename table from financial_indicator to stock_financial
    op.rename_table('financial_indicator', 'stock_financial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename table back from stock_financial to financial_indicator
    op.rename_table('stock_financial', 'financial_indicator')
    
    # Drop symbol column
    op.drop_column('financial_indicator', 'symbol')
    # ### end Alembic commands ###
