"""add financial indicator table

Revision ID: eec6febc30ca
Revises: 5f4c9e8a6bf5
Create Date: 2026-02-20 19:15:00.592242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec6febc30ca'
down_revision = '5f4c9e8a6bf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('third_code', sa.String(length=32), nullable=False),
    sa.Column('ann_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('eps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('dt_eps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_revenue_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('revenue_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('capital_rese_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('surplus_rese_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('undist_profit_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('extra_item', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('profit_dedt', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cash_ratio', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ar_turn', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ca_turn', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('fa_turn', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('assets_turn', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('op_income', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('ebit', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('fcff', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('fcfe', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('current_exint', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('noncurrent_exint', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('interestdebt', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('netdebt', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('tangible_asset', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('networking_capital', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('invest_capital', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('retained_earnings', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('diluted2_eps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('bps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ocfps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('retainedps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cfps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ebit_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('fcff_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('fcfe_ps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('netprofit_margin', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('grossprofit_margin', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cogs_of_sales', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('expense_of_sales', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('profit_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('saleexp_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('adminexp_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('finaexp_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('impai_ttm', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('gc_of_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('op_of_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ebit_of_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roe_waa', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roe_dt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('npta', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roic', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roe_yearly', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roa2_yearly', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('debt_to_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('assets_to_eqt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('dp_assets_to_eqt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ca_to_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('nca_to_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('tbassets_to_totalassets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('int_to_talcap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('eqt_to_talcap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('currentdebt_to_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('longdeb_to_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ocf_to_shortdebt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ocf_to_interestdebt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ocf_to_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cash_to_liqdebt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cash_to_liqdebt_withinterest', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('op_to_liqdebt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('op_to_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roic_yearly', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('profit_to_op', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_opincome', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('q_investincome', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('q_dtprofit', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('q_eps', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_netprofit_margin', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_gsprofit_margin', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_exp_to_sales', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_profit_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_saleexp_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_adminexp_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_finaexp_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_impai_to_gr_ttm', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_gc_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_op_to_gr', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_roe', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_dt_roe', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_npta', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_opincome_to_ebt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_investincome_to_ebt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_dtprofit_to_profit', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_salescash_to_or', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_ocf_to_sales', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('q_ocf_to_or', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('update_flag', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'third_code', 'end_date', name='uq_financial_indicator_key')
    )
    op.create_index(op.f('ix_financial_indicator_ann_date'), 'financial_indicator', ['ann_date'], unique=False)
    op.create_index(op.f('ix_financial_indicator_end_date'), 'financial_indicator', ['end_date'], unique=False)
    op.create_index(op.f('ix_financial_indicator_source'), 'financial_indicator', ['source'], unique=False)
    op.create_index(op.f('ix_financial_indicator_third_code'), 'financial_indicator', ['third_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_indicator_third_code'), table_name='financial_indicator')
    op.drop_index(op.f('ix_financial_indicator_source'), table_name='financial_indicator')
    op.drop_index(op.f('ix_financial_indicator_end_date'), table_name='financial_indicator')
    op.drop_index(op.f('ix_financial_indicator_ann_date'), table_name='financial_indicator')
    op.drop_table('financial_indicator')
    # ### end Alembic commands ###
